#codigo completo em https://colab.research.google.com/drive/1JDSNb5qA2J-dBgqb5WP2u6lG7UwPFvo9?usp=sharing
# -*- coding: utf-8 -*-
"""graficos_em_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDSNb5qA2J-dBgqb5WP2u6lG7UwPFvo9
"""

# Commented out IPython magic to ensure Python compatibility.
#https://matplotlib.org/stable/gallery/index
import matplotlib.pyplot as plt
# %matplotlib inline

categorias = ["A", "B", "C", "D"]
valores = [1, 10, 100, 1000]

soma_valores = sum(valores)
soma_valores

plt.figure(figsize=(10,10))
plt.pie(valores,
        labels=None,
        autopct='%1.1f%%',
        startangle=140,
        labeldistance=1.1,
        pctdistance=1.2)
plt.title("Grafico de Pizza")
plt.show()

soma_valores

labels_legenda = []
for i in range(len(categorias)):
  porcentagem = round((valores[i] / soma_valores) * 100, 1)
  labels_legenda.append(f"{categorias[i]} - {porcentagem}%")

fig, ax = plt.subplots(figsize=(8,8))

patches, texts = ax.pie(
    valores,
    labels=None,
    startangle=140
)

ax.legend(patches, labels_legenda, title="Categorias", loc="best")

plt.title("Grafico de Pizza")
plt.show()

